modulos/midia/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns("micro.modulos.midia.views",   
    (r'^$', 'midia_view'),    
    (r'^informativo/$', 'informativo_view'),
    (r'^noticias/(?P<pagina>.*)/$', 'noticias_view'),
    (r'^noticia/(?P<titulo_slug>.*)/$', 'noticia_view'),
    (r'^hotsites/$', 'hotsites_view'),
    (r'^manual_da_marca/$', 'manual_da_marca_view'),
    (r'^publicidade/$', 'publicidade_view'),
    (r'^teste_aplicativo/$', 'teste_aplicativo'),
)    

modulos/rh/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns("micro.modulos.rh.views",   
    (r'^$', 'rh_view'),    
    (r'^adicionar_foto/(?P<id_curriculo>.*)/$', 'editar_foto_view'),
    (r'^cropar/(?P<id_curriculo>.*)/$', 'cropar_foto_view'),
    (r'^curriculo/(?P<id_curriculo>.*)/$', 'rh_curriculo_editar_view'),
    (r'^curriculo/$', 'rh_curriculo_view'),
    (r'^logout/$', 'logout_view'), 
)    

modulos/suporte/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns("micro.modulos.suporte.views",   
    (r'^$', 'suporte_view'),
    (r'^catalogos/$', 'catalogos_view'),
    (r'^manuais/$', 'manuais_view'),
    (r'^perguntas_frequentes/$', 'perguntas_view'),
)    

urls.py
#-*- coding: utf-8 -*-
##############################################
from django.conf.urls.defaults import *
from django.conf import settings
#############################################
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^generico/', include('generico.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #Sombreamentos de URL's no admin
    (r'^admin/midia/', include('micro.modulos.midia.admin_urls')),
    (r'^admin/suporte/', include('micro.modulos.suporte.admin_urls')),
    (r'^admin/rh/', include('micro.modulos.rh.admin_urls')),
    (r'^admin/atendimento_microsol/', include('micro.modulos.atendimento_microsol.admin_urls')),
    (r'^admin/onde_encontrar/', include('micro.modulos.onde_encontrar.admin_urls')),
    (r'^admin/catalogo/', include('micro.modulos.catalogo.admin_urls')),
    (r'^admin/a_microsol/', include('micro.modulos.a_microsol.admin_urls')),
    (r'^admin/fale_conosco/', include('micro.modulos.fale_conosco.admin_urls')),
    (r'^admin/site_config/siteconfig/$', 'micro.modulos.site_config.views.sombreamento_siteconfig'),
    (r'^admin/site_config/homepage/$', 'micro.modulos.site_config.views.sombreamento_homepage'),
    (r'^admin/(.*)', admin.site.root),
    
    (r'^$', 'micro.modulos.site_config.views.home_view'),
    (r'^microsol_e_voce/$', 'micro.modulos.site_config.views.microsol_e_voce_view'),
    (r'^teste_pdf/$', 'micro.modulos.site_config.views.teste_pdf_view'),
    (r'^cadastrar_newsletter_ajax/$', 'micro.modulos.newsletter.views.cadastrar_newsletter_ajax'),
    (r'^fale_conosco/', include('micro.modulos.fale_conosco.urls')),
    (r'^produtos/', include('micro.modulos.produtos.urls')),
    (r'^midia/', include('micro.modulos.midia.urls')),
    (r'^suporte/', include('micro.modulos.suporte.urls')),
    (r'^rh/', include('micro.modulos.rh.urls')),
    (r'^atendimentoonsite/', include('micro.modulos.atendimento_microsol.urls')),
    (r'^microsol_e_voce/aplicativo/(?P<potencia>.*)/(?P<delimitador>.*)/$', 'micro.modulos.produtos.views.aplicativo_microsol_e_voce'),
    (r'^a_microsol_indica/$', 'micro.modulos.a_microsol.views.aplicativo_view'),
    (r'^onde_encontrar/', include('micro.modulos.onde_encontrar.urls')),
    (r'^catalogos/', include('micro.modulos.catalogo.urls')),
    (r'^a_microsol/', include('micro.modulos.a_microsol.urls')),
    (r'^utils/', include('micro.modulos.urls')),
    (r'^__swf/(.*)', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + "/swf/"}),    
 #   (r'^__swf/banner1.swf', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + "/swf/banner1.swf"}),    
 #   (r'^__swf/banner2.swf', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + "/swf/banner2.swf"}),    
 #   (r'^__swf/banner3.swf', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + "/swf/banner3.swf"}),    
    (r'^site_media/(.*)', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),    

)

modulos/atendimento_microsol/models.py
#-*- coding: utf-8 -*-
from django.db import models

class Chamada(models.Model):
    nome = models.CharField(u"Nome", max_length = 196, blank = True, null = True)
    setor = models.CharField(u"Setor", max_length = 196, blank = True, null = True)
    orgao_solicitante = models.CharField(u"Orgão Solicitante", max_length = 196, blank = True, null = True)
    ordem_consoft = models.CharField(u"Ordem Consoft", max_length = 196, blank = True, null = True)
    endereco = models.CharField(u"Endereço", max_length = 196, blank = True, null = True)
    numero = models.CharField(u"Número", max_length = 196, blank = True, null = True)
    complemento = models.CharField(u"Complemento", max_length = 196, blank = True, null = True)
    cep = models.CharField(u"CEP", max_length = 196, blank = True, null = True)
    bairro = models.CharField(u"Bairro", max_length = 196, blank = True, null = True)
    estado = models.CharField(u"Estado", max_length = 196, blank = True, null = True)
    cidade = models.CharField(u"Cidade", max_length = 196, blank = True, null = True)
    telefone = models.CharField(u"Telefone", max_length = 196, blank = True, null = True)
    numero_de_tombamento = models.CharField(u"Número de Tombamento", max_length = 196, blank = True, null = True)     
    email = models.EmailField(u"Email", blank = True, null = True)
    modelo_equipamento = models.CharField(u"Modelo do Equipamento", max_length = 196, blank = True, null = True)
    numero_de_serie = models.CharField(u"Número de Série", max_length = 196, blank = True, null = True)
    potencia = models.CharField(u"Potência", max_length = 196, blank = True, null = True)
    numero_nota_fiscal = models.CharField(u"N de série da Nota Fiscal", max_length = 196, blank = True, null = True)
    descricao_problema = models.TextField(u"Descrição do Problema", blank = True, null = True)
    solucionado = models.BooleanField(u"Solucionado")
    data_solucao = models.DateTimeField(u"Data da solução", blank = True, null = True)
    data = models.DateTimeField(u"Cadastrado em", auto_now_add = True, blank = True, null = True)
    
    class Meta:
        verbose_name = u"Chamada"
        verbose_name_plural = u"Chamada"

    def __str__(self):
        return u"Chamada #%s" % self.id

    def __unicode__(self):
        return u"Chamada #%s" % self.id    
    
class PaginaAtendimentoMicrosol(models.Model):
    titulo = models.CharField(u"Título", max_length = 196, blank = True, null = True, help_text = "")
    texto = models.TextField(u"Texto", blank = True, null = True, help_text = "")
    seo_titulo = models.CharField(u"Título", max_length = 128, blank = True, null = True, help_text = "")
    seo_descricao = models.TextField(u"Descrição", blank = True, null = True, help_text = "")
    seo_tags = models.CharField(u"Tags", max_length = 255, blank = True, null = True, help_text = "")

    class Meta:
        verbose_name = "Pagina Atendimento Microsol"
        verbose_name_plural = "Pagina Atendimento Microsol"

    def __str__(self):
        return u""

    def __unicode__(self):
        return u""    
    

modulos/atendimento_microsol/forms.py
#-*- coding:utf-8 -*-
from django.forms import ModelForm
from models import Chamada

class FormChamada(ModelForm):
    class Meta:
        model = Chamada

modulos/rh/forms.py
#-*- coding:utf-8 -*-
from django.forms import ModelForm
from models import Curriculo

class FormCurriculo(ModelForm):
    class Meta:
        model = Curriculo
        exclude = ('foto', )
        
class FormCurriculoFoto(ModelForm):
    class Meta:
        model = Curriculo
        fields = ('foto', )

modulos/a_microsol/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from models import PaginaAMicrosol, PaginaAEmpresa, PaginaConheca, PaginaQualidadeEPremios
from micro.modulos.site_config.models import SiteConfig

#Sombreamento do Admin
def sombreamento_pagina_a_microsol(request):
    pagina, criado = PaginaAMicrosol.objects.get_or_create(id = 1)
    return HttpResponseRedirect('/admin/a_microsol/paginaamicrosol/1/')

def sombreamento_pagina_a_empresa(request):
    pagina, criado = PaginaAEmpresa.objects.get_or_create(id = 1)
    return HttpResponseRedirect('/admin/a_microsol/paginaaempresa/1/')

def sombreamento_pagina_conheca(request):
    pagina, criado = PaginaConheca.objects.get_or_create(id = 1)
    return HttpResponseRedirect('/admin/a_microsol/paginaconheca/1/')

def sombreamento_pagina_qualidade_e_premios(request):
    pagina, criado = PaginaQualidadeEPremios.objects.get_or_create(id = 1)
    return HttpResponseRedirect('/admin/a_microsol/paginaqualidadeepremios/1/')

#VIews do site
def a_microsol_view(request):
    config = SiteConfig.objects.get(id = 1)
    pagina = PaginaAMicrosol.objects.get(id = 1)
    variaveis = RequestContext(request, {'pagina': pagina, 'config': config})
    return render_to_response('a_microsol.html', variaveis)

def a_empresa_view(request):
    config = SiteConfig.objects.get(id = 1)
    pagina = PaginaAEmpresa.objects.get(id = 1)
    variaveis = RequestContext(request, {'pagina': pagina, 'config': config})
    return render_to_response('a_microsol_empresa.html', variaveis)

def conheca_view(request):
    config = SiteConfig.objects.get(id = 1)
    pagina = PaginaConheca.objects.get(id = 1)
    variaveis = RequestContext(request, {'pagina': pagina, 'config': config})
    return render_to_response('a_microsol_conheca.html', variaveis)

def qualidade_e_premios_view(request):
    config = SiteConfig.objects.get(id = 1)
    pagina = PaginaQualidadeEPremios.objects.get(id = 1)
    variaveis = RequestContext(request, {'pagina': pagina, 'config': config})
    return render_to_response('a_microsol_qualidadepremios.html', variaveis)

def aplicativo_view(request):
    config = SiteConfig.objects.get(id = 1)
    variaveis = RequestContext(request, {'config': config})
    return render_to_response('microsol_e_voce.html', variaveis)
    

modulos/atendimento_microsol/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.mail import send_mail, EmailMessage
from models import PaginaAtendimentoMicrosol, Chamada
from forms import FormChamada
from micro.modulos.site_config.models import SiteConfig
from datetime import date

#Sombreamento do Admin
def sombreamento_pagina_atendimento_microsol(request):
    pagina, criado = PaginaAtendimentoMicrosol.objects.get_or_create(id = 1)
    return HttpResponseRedirect('/admin/atendimento_microsol/paginaatendimentomicrosol/1/')

#VIews do site
def atendimento_microsol_view(request):
    config = SiteConfig.objects.get(id = 1)
    pagina = PaginaAtendimentoMicrosol.objects.get(id = 1)
    cadastrado = False
    novo_cadastro = FormChamada()
    if request.method == "POST":
        novo_cadastro = FormChamada(request.POST)
        if novo_cadastro.is_valid():
            novo_objeto = novo_cadastro.save()
            novo_objeto.telefone = "(%s) %s %s" % (request.POST['ddd'], request.POST['fone'], request.POST['ramal'])
            novo_objeto.cep = "%s %s" % (request.POST['cep_1'], request.POST['cep_2'])
            novo_objeto.save()
            cadastrado = True
            mensagem_email = u"""
                <div align="center">
	<table width="545" cellspacing="3" cellpadding="0" border="0" style="font-family: Verdana,Arial,Helvetica,sans-serif; font-size: 11px;">
		<tbody><tr>
			<td width="220" style="font-size: 14px;" colspan="2">
				<div align="center">
					<strong>CONTATO ENVIADO ATRAVÉS DO ATENDIMENTO ON SITE MICROSOL <a onclick="onClickUnsafeLink(event);" target="_blank">www.microsol.com.br</a></strong>
				</div>
			</td>
		</tr>
		<tr>
			<td width="223"> </td>
			<td width="313"> </td>
		</tr>
		<tr>
			<td><strong>NÚMERO DA SOLICITAÇÃO:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>SETOR:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>ORGÃO SOLICITADOR:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>ORDEM CONSOFT:</strong></td>
			<td>%s<td/>
		</tr>
		<tr>
			<td><strong>NÚMERO D0 TOMBAMENTO:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>ENDEREÇO:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>COMPLEMENTO:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>NÚMERO:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>BAIRRO:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>CEP:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>CIDADE:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>ESTADO:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>EMAIL:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>TELEFONE:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>MODELO DO EQUIPAMENTO:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>NÚMERO DE SÉRIE EQUIPAMENTO:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>POTÊNCIA:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>NOTA FISCAL:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td><strong>PROBLEMA:</strong></td>
			<td>%s</td>
		</tr>
		<tr>
			<td/>
			<td/>
		</tr>
		<tr>
			<td width="220" colspan="2"><div align="center">
				<strong><i>Esta é uma mensagem automática, por favor não responda</i></strong></div></td>
		</tr>
	</tbody></table>
</div>

"""  % (novo_objeto.id, novo_objeto.setor, novo_objeto.orgao_solicitante, novo_objeto.ordem_consoft, novo_objeto.numero_de_tombamento,
        novo_objeto.endereco, novo_objeto.complemento, novo_objeto.numero, novo_objeto.bairro, novo_objeto.cep, novo_objeto.cidade, 
        novo_objeto.estado, novo_objeto.email, novo_objeto.telefone, novo_objeto.modelo_equipamento, novo_objeto.numero_de_serie, 
        novo_objeto.potencia, novo_objeto.numero_nota_fiscal, novo_objeto.descricao_problema)
            enviar_email = EmailMessage("Atendimento on site - www.microsol.com.br‏", mensagem_email, "microsol@microsol.com", (
            novo_objeto.email, "silvio@indexvirtual.com"))
            enviar_email.content_subtype = "html"
            enviar_email.send(fail_silently = False)
            return HttpResponse("sucesso")  
    variaveis = RequestContext(request, {'formulario': novo_cadastro, 'pagina': pagina, 'config': config, 'cadastrado': cadastrado})
    return render_to_response('atendimento_microsol.html', variaveis)



modulos/catalogo/views.py
#-*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from models import PaginaCatalogos
from micro.modulos.site_config.models import SiteConfig
from django.template.defaultfilters import slugify
from micro.modulos.index_gallery.models import Galeria

#Sombreamento do Admin
def sombreamento_pagina_catalogos(request):
    pagina, criado = PaginaCatalogos.objects.get_or_create(id = 1)
    return HttpResponseRedirect('/admin/catalogo/paginacatalogos/1/')

#VIews do site
def catalogo_view(request, id_galeria = None):
    config = SiteConfig.objects.get(id = 1)
    pagina = PaginaCatalogos.objects.get(id = 1)
    if id_galeria:
        catalogo = Galeria.objects.get(nome_slug = id_galeria)
        xml = "%s.xml" % slugify(catalogo.nome)
        titulo = catalogo.nome
    else:
        xml = "%s.xml" % slugify(pagina.catalogo_destaque.nome)
        titulo = pagina.catalogo_destaque.nome
    variaveis = RequestContext(request, {'config': config, 'pagina': pagina, 'titulo': titulo, 'xml': xml})
    return render_to_response('catalogo.html', variaveis)
    

templates/aplicativo.html
{% extends "base.html" %}
{% block "extrahead" %}
    <script type="text/javascript" >
         function filtrar_produtos(potencia, delimitador){
             $.ajax({
                 url: "http://micro.indexvirtual.com/microsol_e_voce/aplicativo/"+ potencia +"/"+ delimitador +"/",
                 type: "GET",
                 async: false,
                 success: function(responseText, responseStatus){
                     alert(responseText);
                 }
             });
         }
    </script>
{% endblock %}
{% block "conteudo" %}
    <a href="javascript: filtrar_produtos(50, 250); void(0);">Televisão</a>
{% endblock %}

templates/catalogo.html
{% extends "base.html" %}
{% block "extrahead" %}
    <script language="javascript">AC_FL_RunContent = 0;</script>
    <script src="{{MEDIA_URL}}js/AC_RunActiveContent.js" language="javascript"></script>
{% endblock %}
{% block "conteudo" %}
    <div id="categoria" class="grid_12">
        <h2>Catálogos</h2>
        <ul>
            {% for catalogo in pagina.catalogos_ordenados %}
                <li><a href="/catalogos/{{catalogo.nome_slug}}/" title="Manuais">{{catalogo.nome}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="clr">&nbsp;</div>
    
    <div id="catalogos" class="grid_12">
    	<script language="javascript">
	if (AC_FL_RunContent == 0) {
		alert("This page requires AC_RunActiveContent.js.");
	} else {
		AC_FL_RunContent(
			'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0',
			'width', '750',
			'height', '600',
			'src', 'http://media.indexvirtual.com/microsol/swf/catalogo',
			'quality', 'high',
			'pluginspage', 'http://www.macromedia.com/go/getflashplayer',
			'align', 'middle',
			'play', 'true',
			'loop', 'true',
			'scale', 'showall',
			'wmode', 'opaque',
			'devicefont', 'false',
			'id', 'catalogo',
			'bgcolor', '#ffffff',
			'name', 'http://media.indexvirtual.com/microsol/swf/catalogo',
			'menu', 'true',
			'allowFullScreen', 'false',
			'allowScriptAccess','always',
			'movie', 'http://media.indexvirtual.com/microsol/swf/catalogo',
			'FlashVars', 'imgURL={{MEDIA_URL}}xml/{{xml}}',
			'salign', ''
			); //end AC code
	}
    </script>
    <noscript>
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="750" height="600" id="catalogo" align="middle">
	<param name="allowScriptAccess" value="always" />
	<param name="FlashVars" value="imgURL={{MEDIA_URL}}xml/{{pagina.catalogo_destaque.nome|slugify}}.xml" />
	<param name="allowFullScreen" value="false" />
	<param name="movie" value="{{MEDIA_URL}}swf/catalogo.swf" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" />	<embed src="{{MEDIA_URL}}swf/catalogo.swf" quality="high" bgcolor="#ffffff" width="750" height="600" name="catalogo" align="middle" allowScriptAccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
	</object>
    </noscript>
    </div>
    
    <div class="clear">&nbsp;</div>
    
    
{% endblock %}

templates/fale_conosco_contato.html
{% extends "base.html" %}
{% block "extrahead" %}
    <script type="text/javascript" src="{{MEDIA_URL}}js/cidade_estados.js" ></script>
    <script type="text/javascript" src="{{MEDIA_URL}}js/jquery-maskedinput.js" ></script>
    <script src="{{MEDIA_URL}}js/validacao.js" type="text/javascript" ></script>
    <script type="text/javascript">
        window.onload = function() {
new dgCidadesEstados(document.getElementById('id_estado'), document.getElementById('id_cidade'), true);
}
    $(document).ready(function(){
        $("#id_ddd").mask("(99)");
        $("#id_telefone").mask("9999-9999");
    });

    function enviar_formulario(){
            if (validarNome($("#id_nome").val()) == false){
                $("#erros").html("Preencha o campo nome corretamente."); 
            }
            else if (validarEmail($("#id_email").val()) == false){
                $("#erros").html("Preencha o campo email corretamente.");
            }      
            else if ($("#id_ddd").val() == "" || $("#id_ddd").val() == "(__)"){
                $("#erros").html("Informe o DDD do seu telefone.");
            }
            else if ($("#id_telefone").val() == "" || $("#id_telefone").val() == "____-____"){
                $("#erros").html("Informe o seu telefone.");
            }
            else if ($("#id_estado").val() == ""){
                $("#erros").html("Informe seu estado.");
            }
            else if ($("#id_cidade").val() == ""){
                $("#erros").html("Informe sua cidade.");
            }
            else if ($("#id_mensagem").val() == ""){
                $("#erros").html("Informe a mensagem.");
            }    
            else {
                $("#id_form_faleconosco").submit();
            }
        }
    </script>
{% endblock %}
{% block "conteudo" %}
	<div id="categoria" class="grid_12">
        <h2>Fale Conosco</h2>
        <ul>
            <li><a href="/fale_conosco/sam/" title="Serviço de Atendimento Microsol">Serviço de Atendimento Microsol</a></li>
            <li><a href="/fale_conosco/contato/" class="sub-ativo" title="Contato">Contato</a></li>
        </ul>
    </div>
    <div class="clr">&nbsp;</div>
    <div id="erros" class="grid_12"></div>
    {% if enviado %}
        <div id="erros" class="grid_12">Mensagem enviada com sucesso!</div>
    {% endif %}
    <div id="faleconosco" class="grid_12">
        <form action="." id="id_form_faleconosco" method="POST">
        	<fieldset>
                <legend>Contato</legend>
                
                <div class="grid_6 alpha">
                	<label>Nome</label>
                    <input type="text" class="ipt_faleconosco" id="id_nome" name="nome"/>
                    <br />
                    
                    <div class="grid_4 alpha">
                        <label>E-mail</label>
                        <input type="text" class="ipt_email" id="id_email" name="email"/>
                    </div>
                    
                    <div class="grid_2 omega">
                    <label>DDD/Telefone</label>
                    <input type="text" class="ipt_ddd" id="id_ddd" name="ddd"/>
                    <input type="text" class="ipt_fone" id="id_telefone" name="telefone"/>
                    </div>
                    <div class="clear">&nbsp;</div>
                    
                    <div class="grid_2 alpha">
                        <label>Setor</label>
                        <select id="id_setor" name="setor">
                            <option "Comercial">Comercial</option>
                            <option "Marketing">Marketing</option>
                        </select>
                    </div>
                    
                    <div class="grid_2">
                        <label>Estado</label>
                        <select id="id_estado" name="estado">
                            <option value="Selecione">Selecione</option>
                            <option value="AC">AC</option>
                            <option value="AL">AL</option>
                            <option value="AM">AM</option>
                            <option value="AP">AP</option>
                            <option value="BA">BA</option>
                            <option value="CE">CE</option>
                            <option value="DF">DF</option>
                            <option value="ES">ES</option>
                            <option value="GO">GO</option>
                            <option value="MA">MA</option>
                            <option value="MG">MG</option>
                            <option value="MS">MS</option>
                            <option value="MT">MT</option>
                            <option value="PA">PA</option>
                            <option value="PB">PB</option>
                            <option value="PE">PE</option>
                            <option value="PI">PI</option>
                            <option value="PR">PR</option>
                            <option value="RJ">RJ</option>
                            <option value="RN">RN</option>
                            <option value="RO">RO</option>
                            <option value="RR">RR</option>
                            <option value="RS">RS</option>
                            <option value="SC">SC</option>
                            <option value="SE">SE</option>
                            <option value="SP">SP</option>
                            <option value="TO">TO</option>
                        </select>
                    </div>
                    
                    <div class="grid_2 omega">
                        <label>Cidade</label>
                        <select id="id_cidade" name="cidade">
                            <option>Selecione</option>
                        </select>
                    </div>
                    <div class="clear">&nbsp;</div>
                </div>
                
                <div class="grid_6 omega">
                    <label>Mensagem</label>
                    <textarea id="id_mensagem" name="mensagem"></textarea>
                    <br />
                    
                    <input type="checkbox" class="cbx" checked /> <label class="lbl_cbx">Desejo receber novidades da Microsol</label>
                </div>
                <div class="clear">&nbsp;</div>
                
                <a href="javascript: enviar_formulario(); void(0);" class="btn btn-enviar fr" title="Enviar">Enviar</a>
            </label>
        </form>
    </div>
    <div class="clear">&nbsp;</div>
{% endblock %}